// GENERATED by tools/fonts/vendor-fonts.mjs — do not edit by hand.
import type { TmFontSubset } from './font-subsets';

/** The Latin/Mono subsets shipped in @tellma/core-ui. */
export const TM_FONTS_LATIN: readonly TmFontSubset[] = [
  {
    family: 'Noto Sans',
    script: 'latin',
    style: 'normal',
    weight: '100 900',
    url: 'fonts/noto-sans-latin-wght-normal.51ca196f49.woff2',
    unicodeRange: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Noto Sans',
    script: 'latin-ext',
    style: 'normal',
    weight: '100 900',
    url: 'fonts/noto-sans-latin-ext-wght-normal.6d5a793155.woff2',
    unicodeRange: 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
  },
  {
    family: 'Noto Sans Mono',
    script: 'latin',
    style: 'normal',
    weight: '400',
    url: 'fonts/noto-sans-mono-latin-400-normal.1e4b885e90.woff2',
    unicodeRange: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
  {
    family: 'Noto Sans Mono',
    script: 'latin',
    style: 'normal',
    weight: '700',
    url: 'fonts/noto-sans-mono-latin-700-normal.20ef1d988a.woff2',
    unicodeRange: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  },
];
