// Copyright (c) Tellma Ltd. All rights reserved.
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.

using Microsoft.Playwright;
using Tellma.Identity.E2E.Infrastructure;

namespace Tellma.Identity.E2E
{
    /// <summary>
    ///     The brand tokens render for real: the emitted @tellma/core-ui-tokens stylesheet loads,
    ///     its custom properties resolve in the page, and the UI consumes them — guarding against a
    ///     broken link, a stale copy, or a variable-vocabulary mismatch between tokens.css and
    ///     identity.css.
    /// </summary>
    [Collection(E2ECollectionDefinition.Name)]
    [Trait("Category", "E2E")]
    public sealed class BrandingTests(PlaywrightFixture playwright, IdentityServerFixture server)
    {
        [Fact]
        public async Task Login_page_loads_and_resolves_the_brand_tokens()
        {
            await using IBrowserContext context = await playwright.Browser.NewContextAsync(
                new BrowserNewContextOptions { BaseURL = server.BaseAddress });
            IPage page = await context.NewPageAsync();

            // The emitted tokens stylesheet is served and is the generated build, not a placeholder.
            IAPIResponse tokens = await page.APIRequest.GetAsync(
                server.BaseAddress + "/_content/Tellma.Identity/css/tokens.css");
            Assert.Equal(200, tokens.Status);
            Assert.Contains("GENERATED by @tellma/core-ui-tokens", await tokens.TextAsync(), StringComparison.Ordinal);

            await page.GotoAsync("/Identity/Account/Login");

            // The action-primary token resolves to the brand teal-600 on the root element.
            string primary = await page.EvaluateAsync<string>(
                "() => getComputedStyle(document.documentElement).getPropertyValue('--color-primary').trim()");
            Assert.Equal("#316E80", primary, ignoreCase: true);

            // identity.css consumes the tokens: the page paints the brand surface and the primary
            // button paints the action color (computed as rgb, resolved through the var chain).
            string pageBackground = await page.EvaluateAsync<string>(
                "() => getComputedStyle(document.body).backgroundColor");
            Assert.Equal("rgb(254, 254, 254)", pageBackground);

            string buttonBackground = await page.EvaluateAsync<string>(
                "() => getComputedStyle(document.querySelector('.tl-button-primary')).backgroundColor");
            Assert.Equal("rgb(49, 110, 128)", buttonBackground);

            // The multi-script brand font stack is applied (the faces themselves are vendored).
            string fontFamily = await page.EvaluateAsync<string>(
                "() => getComputedStyle(document.body).fontFamily");
            Assert.Contains("Noto Sans", fontFamily, StringComparison.Ordinal);
        }
    }
}
