// Copyright (c) Tellma Ltd. All rights reserved.
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.

/**
 * The identity server's vendored font set, defined once so the copier and the
 * drift gate cannot disagree about it.
 *
 * The .NET build has no Node toolchain, so the identity RCL commits copies of
 * assets that live here. Its stylesheet is a composition rather than a copy:
 * the core Latin faces plus every locale pack's script, concatenated into one
 * file, because the server has no bundler to assemble them at build time.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const clientDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** One source of vendored faces: a generated stylesheet plus the files it names. */
export interface FontSource {
  /** Absolute path to the folder holding the stylesheet and its woff2 files. */
  readonly dir: string;
  /** What this source contributes, for the composed file's section comment. */
  readonly label: string;
}

/** The sources composed into the identity server's stylesheet, in cascade order. */
export const identityFontSources: readonly FontSource[] = [
  {
    dir: join(clientDir, 'projects', 'core', 'tellma-core-ui', 'fonts'),
    label: 'Latin + Mono (core)',
  },
  {
    dir: join(clientDir, 'projects', 'locale', 'tellma-locale-ar', 'fonts'),
    label: 'Arabic (locale pack)',
  },
];

/**
 * Strips a generated file's own license/provenance header so the composition
 * carries exactly one, rather than one per source.
 */
function body(css: string): string {
  // Every generated stylesheet opens with a block comment; the faces follow it.
  const end = css.indexOf('*/');
  const withoutHeaders = end < 0 ? css : css.slice(end + 2);
  return withoutHeaders.replace(/^\s*\/\*[\s\S]*?\*\/\s*/, '').trim();
}

/**
 * Builds the identity server's fonts.css from the vendored sources.
 *
 * @returns The composed stylesheet, newline-terminated.
 */
export function composeIdentityFontsCss(): string {
  const header = [
    '/*',
    ' * Copyright (c) Tellma Ltd. All rights reserved.',
    ' *',
    ' * This source code is licensed under the Apache-2.0 license found in the',
    ' * LICENSE file in the root directory of this source tree.',
    ' */',
    '',
    '/* GENERATED by tools/fonts/copy-identity-fonts.mts — do not edit by hand.',
    '   Self-hosted Noto subsets (SIL OFL 1.1 — see OFL.txt), composed from the',
    '   core faces and every locale pack. unicode-range keeps a face from',
    '   downloading until the page actually renders its script. */',
    '',
  ].join('\n');

  const sections = identityFontSources.map(
    (source) => `/* ${source.label} */\n${body(readFileSync(join(source.dir, 'fonts.css'), 'utf8'))}`,
  );

  return `${header}\n${sections.join('\n\n')}\n`;
}

/**
 * The woff2 files the composed stylesheet references, as absolute source paths.
 *
 * @returns Absolute paths to every vendored font file.
 */
export function identityFontFiles(): string[] {
  const files: string[] = [];
  for (const source of identityFontSources) {
    const css = readFileSync(join(source.dir, 'fonts.css'), 'utf8');
    for (const match of css.matchAll(/url\(\.\/([^)]+\.woff2)\)/g)) {
      files.push(join(source.dir, match[1]));
    }
  }

  return files;
}
