// Copyright (c) Tellma Ltd. All rights reserved.
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.

/**
 * One-shot font vendoring (spec §7.1, D10): copies the Noto woff2 subsets out
 * of the Fontsource packages (dev-only vendoring source) into the library's
 * fonts/ assets, and generates:
 *   - fonts/fonts.css       (@font-face + unicode-range + font-display:swap)
 *   - fonts/OFL.txt         (SIL Open Font License — must ship with the fonts)
 * The copied binaries are COMMITTED so the published package is fully
 * self-contained (intranet-safe, no CDN). Re-run only to refresh versions.
 *
 * Usage: node tools/fonts/vendor-fonts.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

import { fallbackFace } from './fallback-face.mjs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const clientDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const uiDir = join(clientDir, 'projects', 'core', 'tellma-core-ui');
const fontsDir = join(uiDir, 'fonts');
mkdirSync(fontsDir, { recursive: true });

// The generated stylesheet is committed, so it carries the license header.
const LICENSE_CSS = [
  '/*',
  ' * Copyright (c) Tellma Ltd. All rights reserved.',
  ' *',
  ' * This source code is licensed under the Apache-2.0 license found in the',
  ' * LICENSE file in the root directory of this source tree.',
  ' */',
  '',
].join('\n');

/** Pulls { file, unicodeRange } for a subset out of a Fontsource css file. */
function extractBlock(cssPath, filePattern) {
  const css = readFileSync(cssPath, 'utf8');
  for (const block of css.split('@font-face')) {
    const file = block.match(/files\/([\w.-]+\.woff2)/)?.[1];
    if (file && filePattern.test(file)) {
      const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
      return { file, unicodeRange };
    }
  }
  throw new Error(`No @font-face matching ${filePattern} in ${cssPath}`);
}

const notoSansDir = join(clientDir, 'node_modules', '@fontsource-variable', 'noto-sans');
const monoDir = join(clientDir, 'node_modules', '@fontsource', 'noto-sans-mono');

const subsets = [
  {
    ...extractBlock(join(notoSansDir, 'index.css'), /^noto-sans-latin-wght-normal/),
    from: notoSansDir,
    family: 'Noto Sans',
    script: 'latin',
    weight: '100 900',
    format: 'woff2-variations',
  },
  {
    ...extractBlock(join(notoSansDir, 'index.css'), /^noto-sans-latin-ext-wght-normal/),
    from: notoSansDir,
    family: 'Noto Sans',
    script: 'latin-ext',
    weight: '100 900',
    format: 'woff2-variations',
  },
  {
    ...extractBlock(join(monoDir, '400.css'), /^noto-sans-mono-latin-400-normal/),
    from: monoDir,
    family: 'Noto Sans Mono',
    script: 'latin',
    weight: '400',
    format: 'woff2',
  },
  {
    ...extractBlock(join(monoDir, '700.css'), /^noto-sans-mono-latin-700-normal/),
    from: monoDir,
    family: 'Noto Sans Mono',
    script: 'latin',
    weight: '700',
    format: 'woff2',
  },
];

// 1. Copy the binaries. The app build pipeline fingerprints them into
// media/ like any other CSS-referenced asset, so the committed names stay
// stable.
for (const subset of subsets) {
  writeFileSync(join(fontsDir, subset.file), readFileSync(join(subset.from, 'files', subset.file)));
}

// 2. fonts.css — self-hosted @font-face; the app adds this sheet to its
// build's `styles`, and the pipeline rewrites/fingerprints the URLs.
const css = [
  LICENSE_CSS,
  '/* GENERATED by tools/fonts/vendor-fonts.mjs — do not edit by hand.',
  '   Self-hosted Noto subsets (SIL OFL 1.1 — see OFL.txt). unicode-range',
  '   keeps a face from downloading until the page shows its script. */',
  '',
  ...subsets.map((s) =>
    [
      '@font-face {',
      `  font-family: '${s.family}';`,
      '  font-style: normal;',
      '  font-display: swap;',
      `  font-weight: ${s.weight};`,
      `  src: url(./${s.file}) format('${s.format}');`,
      `  unicode-range: ${s.unicodeRange};`,
      '}',
      '',
    ].join('\n'),
  ),
  // Metric-adjusted LOCAL fallbacks: text lays out at the web fonts' exact
  // metrics from the first frame, so the font-display swap shifts nothing.
  // unicode-range keeps each fallback to its own web font's scripts.
  fallbackFace({
    family: 'Noto Sans Fallback',
    preferred: 'notoSans',
    fallback: 'arial',
    local: 'Arial',
    unicodeRange: [subsets[0].unicodeRange, subsets[1].unicodeRange].join(','),
  }),
  fallbackFace({
    family: 'Noto Sans Mono Fallback',
    preferred: 'notoSansMono',
    fallback: 'courierNew',
    local: 'Courier New',
    unicodeRange: subsets[2].unicodeRange,
  }),
].join('\n');
writeFileSync(join(fontsDir, 'fonts.css'), css);

// 3. OFL license text (ships alongside the binaries).
const license = readFileSync(join(notoSansDir, 'LICENSE'), 'utf8');
writeFileSync(
  join(fontsDir, 'OFL.txt'),
  'Noto Sans & Noto Sans Mono — SIL Open Font License 1.1\n' +
    'Vendored from the Fontsource packages (fontsource.org).\n\n' +
    license,
);


console.log(`vendored ${subsets.length} subsets -> ${fontsDir}`);
