/**
 * One-shot font vendoring (spec §7.1, D10): copies the Noto woff2 subsets out
 * of the Fontsource packages (dev-only vendoring source) into the library's
 * fonts/ assets, and generates:
 *   - fonts/fonts.css       (@font-face + unicode-range + font-display:swap)
 *   - fonts/OFL.txt         (SIL Open Font License — must ship with the fonts)
 *   - fonts/font-manifest.generated.ts (the TM_FONT_SUBSETS seed)
 * The copied binaries are COMMITTED so the published package is fully
 * self-contained (intranet-safe, no CDN). Re-run only to refresh versions.
 *
 * Usage: node tools/fonts/vendor-fonts.mjs
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const clientDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const uiDir = join(clientDir, 'projects', 'core', 'tellma-core-ui');
const fontsDir = join(uiDir, 'fonts');
mkdirSync(fontsDir, { recursive: true });

/** Pulls { file, unicodeRange } for a subset out of a Fontsource css file. */
function extractBlock(cssPath, filePattern) {
  const css = readFileSync(cssPath, 'utf8');
  for (const block of css.split('@font-face')) {
    const file = block.match(/files\/([\w.-]+\.woff2)/)?.[1];
    if (file && filePattern.test(file)) {
      const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
      return { file, unicodeRange };
    }
  }
  throw new Error(`No @font-face matching ${filePattern} in ${cssPath}`);
}

const notoSansDir = join(clientDir, 'node_modules', '@fontsource-variable', 'noto-sans');
const monoDir = join(clientDir, 'node_modules', '@fontsource', 'noto-sans-mono');

const subsets = [
  {
    ...extractBlock(join(notoSansDir, 'index.css'), /^noto-sans-latin-wght-normal/),
    from: notoSansDir,
    family: 'Noto Sans',
    script: 'latin',
    weight: '100 900',
    format: 'woff2-variations',
  },
  {
    ...extractBlock(join(notoSansDir, 'index.css'), /^noto-sans-latin-ext-wght-normal/),
    from: notoSansDir,
    family: 'Noto Sans',
    script: 'latin-ext',
    weight: '100 900',
    format: 'woff2-variations',
  },
  {
    ...extractBlock(join(monoDir, '400.css'), /^noto-sans-mono-latin-400-normal/),
    from: monoDir,
    family: 'Noto Sans Mono',
    script: 'latin',
    weight: '400',
    format: 'woff2',
  },
  {
    ...extractBlock(join(monoDir, '700.css'), /^noto-sans-mono-latin-700-normal/),
    from: monoDir,
    family: 'Noto Sans Mono',
    script: 'latin',
    weight: '700',
    format: 'woff2',
  },
];

// 1. Copy the binaries under content-hashed names (§7.1): the URL changes
// whenever the bytes do, so the files can be served immutable and a preload
// can never race a stale cache entry.
for (const subset of subsets) {
  const bytes = readFileSync(join(subset.from, 'files', subset.file));
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 10);
  subset.hashedFile = subset.file.replace(/\.woff2$/, `.${hash}.woff2`);
  writeFileSync(join(fontsDir, subset.hashedFile), bytes);
}

// 2. fonts.css — self-hosted @font-face, URLs relative to THIS FILE. The
// stylesheet is served as a static asset next to the binaries (never through
// the app styles pipeline, which would rewrite the URLs away from the
// manifest's), so url(./x) and the manifest's fonts/x resolve identically.
const css = [
  '/* GENERATED by tools/fonts/vendor-fonts.mjs — do not edit by hand.',
  '   Self-hosted Noto subsets (SIL OFL 1.1 — see OFL.txt). unicode-range',
  '   keeps a face from downloading until the page shows its script (§7.1). */',
  '',
  ...subsets.map((s) =>
    [
      '@font-face {',
      `  font-family: '${s.family}';`,
      '  font-style: normal;',
      '  font-display: swap;',
      `  font-weight: ${s.weight};`,
      `  src: url(./${s.hashedFile}) format('${s.format}');`,
      `  unicode-range: ${s.unicodeRange};`,
      '}',
      '',
    ].join('\n'),
  ),
].join('\n');
writeFileSync(join(fontsDir, 'fonts.css'), css);

// 3. OFL license text (ships alongside the binaries).
const license = readFileSync(join(notoSansDir, 'LICENSE'), 'utf8');
writeFileSync(
  join(fontsDir, 'OFL.txt'),
  'Noto Sans & Noto Sans Mono — SIL Open Font License 1.1\n' +
    'Vendored from the Fontsource packages (fontsource.org).\n\n' +
    license,
);

// 4. The TM_FONT_SUBSETS seed manifest (generated TS, committed).
const manifest = [
  '// GENERATED by tools/fonts/vendor-fonts.mjs — do not edit by hand.',
  "import type { TmFontSubset } from './font-subsets';",
  '',
  '/** The Latin/Mono subsets shipped in @tellma/core-ui. */',
  'export const TM_FONTS_LATIN: readonly TmFontSubset[] = [',
  ...subsets.map((s) =>
    [
      '  {',
      `    family: '${s.family}',`,
      `    script: '${s.script}',`,
      `    style: 'normal',`,
      `    weight: '${s.weight}',`,
      `    url: 'fonts/${s.hashedFile}',`,
      `    unicodeRange: '${s.unicodeRange}',`,
      '  },',
    ].join('\n'),
  ),
  '];',
  '',
].join('\n');
writeFileSync(join(uiDir, 'fonts', 'font-manifest.generated.ts'), manifest);

console.log(`vendored ${subsets.length} subsets -> ${fontsDir}`);
