// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tellma.Core.EntityFrameworkCore.MigrationsHost;
using Tellma.Core.EntityFrameworkCore.TableTypes;

#nullable disable

namespace Tellma.Core.EntityFrameworkCore.MigrationsHost.Migrations
{
    [DbContext(typeof(MigrationsHostContext))]
    [Migration("20260611233921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Tellma:TableType:BuiltIn", "{\"types\":15,\"schema\":\"dbo\",\"grants\":[\"public\"]}")
                .HasAnnotation("Tellma:TableTypeStandalone:.DocumentStatesList", "{\"name\":\"DocumentStatesList\",\"isMemoryOptimized\":false,\"grants\":[\"public\"],\"key\":[\"Id\"],\"columns\":[{\"name\":\"Id\",\"clrTypeName\":\"System.Int32, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e\",\"isNullable\":false},{\"name\":\"State\",\"clrTypeName\":\"System.Int16, System.Private.CoreLib, Version=10.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e\",\"isNullable\":false}]}");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("sq_Customers", "crm")
                .StartsAt(10000L);

            modelBuilder.HasSequence<int>("sq_InvoiceLines", "gl")
                .StartsAt(10000L);

            modelBuilder.HasSequence<int>("sq_Invoices", "gl")
                .StartsAt(10000L);

            modelBuilder.HasSequence<int>("sq_Settings", "dbo")
                .StartsAt(10000L);

            modelBuilder.Entity("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.ToTable("Settings", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "System.Version",
                            Value = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            Key = "System.Locale",
                            Value = "en"
                        });
                });

            modelBuilder.Entity("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Customers", "crm");

                    b.HasAnnotation("Tellma:TableType:Grants", "[\"public\"]");
                });

            modelBuilder.Entity("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("TotalWithTax")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19,4)")
                        .HasComputedColumnSql("[Total] * 1.15", true);

                    b.HasKey("Id");

                    b.ToTable("Invoices", "gl");

                    b
                        .HasAnnotation("Tellma:TableType:Enabled", true)
                        .HasAnnotation("Tellma:TableType:Grants", "[\"public\"]");
                });

            modelBuilder.Entity("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines", "gl");

                    b.HasAnnotation("Tellma:TableType:Grants", "[\"public\"]");
                });

            modelBuilder.Entity("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.InvoiceLine", b =>
                {
                    b.HasOne("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tellma.Core.EntityFrameworkCore.MigrationsHost.Model.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.HasTableTypeDefinition("DocumentStatesList", null, type => type
                .Column(name: "Id", storeType: "int")
                .Column(name: "State", storeType: "smallint")
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("CustomersList", "crm", type => type
                .ForTable("Customers", "crm")
                .Column(name: "Id", storeType: "int")
                .Column(name: "LoyaltyPoints", storeType: "int")
                .Column(name: "Name", storeType: "nvarchar(255)", maxLength: 255)
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("BigIdList", "dbo", type => type
                .Column(name: "Id", storeType: "bigint")
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("GuidList", "dbo", type => type
                .Column(name: "Id", storeType: "uniqueidentifier")
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("IdList", "dbo", type => type
                .Column(name: "Id", storeType: "int")
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("StringList", "dbo", type => type
                .Column(name: "Id", storeType: "nvarchar(450)", maxLength: 450)
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("InvoiceLinesList", "gl", type => type
                .ForTable("InvoiceLines", "gl")
                .Column(name: "Id", storeType: "int")
                .Column(name: "InvoiceId", storeType: "int")
                .Column(name: "Description", storeType: "nvarchar(500)", maxLength: 500)
                .Column(name: "Quantity", storeType: "decimal(19,4)")
                .HasKey("Id")
                .HasGrants("public"));

            modelBuilder.HasTableTypeDefinition("InvoicesList", "gl", type => type
                .ForTable("Invoices", "gl")
                .Column(name: "Id", storeType: "int")
                .Column(name: "CustomerId", storeType: "int")
                .Column(name: "Memo", storeType: "nvarchar(255)", nullable: true, maxLength: 255)
                .Column(name: "Total", storeType: "decimal(19,4)")
                .Column(name: "RowVersion", storeType: "binary(8)", nullable: true, maxLength: 8, rowVersion: true)
                .HasKey("Id")
                .HasGrants("public"));
#pragma warning restore 612, 618
        }
    }
}
